server {
    listen 3045;
    server_name _;

    root /usr/share/nginx/html;
    index entry.sh;

    location = / {
        try_files /entry.sh =404;
        default_type text/plain;
    }

    location / {
        try_files $uri =404;
        default_type text/plain;
        add_header Cache-Control "no-store";
    }
}
